SHOW DATABASES;
CREATE DATABASE Customer_behavior;
select * from customer limit 20;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue
from customer
group by gender; 

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select  customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as Average_rating
from customer
group by item_purchased
order by Average_rating desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, round(Avg(purchase_amount),2) as AVR_Amount
from customer
Where shipping_type in ('Standard', 'Express')
group by shipping_type
order by AVR_Amount ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status, count(customer_id) as total_customer, round(sum(purchase_amount),2) as total_revenue, round(avg(previous_purchases),2) as AVR_Spend
from customer 
group by subscription_status
order by total_revenue, AVR_Spend desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100* sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc 
limit 5; 

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
select 
case 
when previous_purchases = 1  then 'New'
when previous_purchases >=2  and previous_purchases <= 10  then 'Returning'
else 'Loyal'
end as customers_segment,
count(*) as Number_of_customer,
sum(previous_purchases) as Total_previous_purchases
from customer
group by customers_segment;


-- Q8. What are the top 3 most purchased products within each category? 
with top_3 as (
select category, item_purchased, count(*) as Number_of_count,
row_number() over (partition by category order by count(*)) as item_rank
from customer
group by category, item_purchased) 

select  item_rank, category, item_purchased, Number_of_count
from top_3
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select count(customer_id) as Total_repeated_buyers , subscription_status
from customer
where previous_purchases > 5 
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as Total_revenue
from customer
group by age_group
order by Total_revenue desc;